### ISSUE TITLE
eslint fails with babel-eslint exception (Node.js 6.2.0)

### ISSUE THREAD

**Issue by boneskull** [bahmutov/ban-sensitive-files#14]
because of this, I had to bypass the hook to commit.

```
$ npm run lint

> ban-sensitive-files@0.0.0-semantic-release lint /Volumes/alien/forked/ban-sensitive-files
> standard bin/*.js src/*.js

TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Volumes/alien/forked/ban-sensitive-files/node_modules/babel-eslint/index.js:220:40)
    at Object.exports.parse (/Volumes/alien/forked/ban-sensitive-files/node_modules/babel-eslint/index.js:362:5)
    at parse (/Volumes/alien/forked/ban-sensitive-files/node_modules/eslint/lib/eslint.js:528:27)
    at EventEmitter.module.exports.api.verify (/Volumes/alien/forked/ban-sensitive-files/node_modules/eslint/lib/eslint.js:652:19)
    at processText (/Volumes/alien/forked/ban-sensitive-files/node_modules/eslint/lib/cli-engine.js:225:27)
    at processFile (/Volumes/alien/forked/ban-sensitive-files/node_modules/eslint/lib/cli-engine.js:262:18)
    at executeOnFile (/Volumes/alien/forked/ban-sensitive-files/node_modules/eslint/lib/cli-engine.js:609:23)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/Volumes/alien/forked/ban-sensitive-files/node_modules/eslint/lib/cli-engine.js:632:56)

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/boneskull/.nvm/versions/node/v6.2.0/bin/node" "/Users/boneskull/.nvm/versions/node/v6.2.0/bin/npm" "run" "lint"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! ban-sensitive-files@0.0.0-semantic-release lint: `standard bin/*.js src/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ban-sensitive-files@0.0.0-semantic-release lint script 'standard bin/*.js src/*.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ban-sensitive-files package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     standard bin/*.js src/*.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ban-sensitive-files
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ban-sensitive-files
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/alien/forked/ban-sensitive-files/npm-debug.log
```

**Comment by bahmutov** [comment]
I upgraded dependencies, do not see the failure on CI or locally https://travis-ci.org/bahmutov/ban-sensitive-files
